baseurl: http://www.zenhappy.org/
title:  Zen Happy
author:
  name: Zen Happy
languageCode: en-nz
metadataformat: yaml
theme: hyde-x
disqusShortname: zenhappy
canonifyurls: false
builddrafts: false
permalinks:
  post: :filename
  archive: archive/:year/:month/:day/:filename
params:
  defaultKeywords: zen,mindful
  highlight: monokai_sublime
  tagline: "A Post a day Keeps the Doctor Away"
  copyright: "Copyright (c) 2000 - 2038 Zen Happy ; all rights reserved."
